name: esalakanmi
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:

  cupertino_icons: ^1.0.2
  file_picker: ^4.5.1
  firebase_storage: ^10.2.16
  flutter:
    sdk: flutter
  geolocator: ^8.2.1
  image_picker: ^0.8.5+3
  shared_preferences: ^2.0.15
  twilio_flutter: ^0.0.9
  url_launcher: ^6.1.2
  uuid: ^3.0.6

dev_dependencies:
  cloud_firestore: ^3.1.8
  firebase: ^9.0.2
  firebase_auth: ^3.3.7
  firebase_core: ^1.12.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  geocoding: ^2.0.4
  intl: ^0.17.0

flutter:

  uses-material-design: true

  assets:
    - assets/
